#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SignatureCapture.Library.Resource", IsApplication=false)]

namespace SignatureCapture.Library
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int background_color = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int paint_color = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int stroke_cap = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int stroke_join = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int stroke_style = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int stroke_width = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030001
			public static int signaturecapture_black = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int signaturecapture_white = 2130903040;
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020004
			public static int bevel = 2130837508;
			
			// aapt resource value: 0x7f020001
			public static int butt = 2130837505;
			
			// aapt resource value: 0x7f020006
			public static int fill = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int fill_and_stroke = 2130837511;
			
			// aapt resource value: 0x7f020003
			public static int miter = 2130837507;
			
			// aapt resource value: 0x7f020000
			public static int round = 2130837504;
			
			// aapt resource value: 0x7f020002
			public static int square = 2130837506;
			
			// aapt resource value: 0x7f020005
			public static int stroke = 2130837509;
			
			private Id()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] signaturecapture = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public static int signaturecapture_background_color = 2;
			
			// aapt resource value: 0
			public static int signaturecapture_paint_color = 0;
			
			// aapt resource value: 3
			public static int signaturecapture_stroke_cap = 3;
			
			// aapt resource value: 4
			public static int signaturecapture_stroke_join = 4;
			
			// aapt resource value: 5
			public static int signaturecapture_stroke_style = 5;
			
			// aapt resource value: 1
			public static int signaturecapture_stroke_width = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
