#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SignatureCapture.Sample.Resource", IsApplication=true)]

namespace SignatureCapture.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			SignatureCapture.Library.Resource.Attribute.background_color = SignatureCapture.Sample.Resource.Attribute.background_color;
			SignatureCapture.Library.Resource.Attribute.paint_color = SignatureCapture.Sample.Resource.Attribute.paint_color;
			SignatureCapture.Library.Resource.Attribute.stroke_cap = SignatureCapture.Sample.Resource.Attribute.stroke_cap;
			SignatureCapture.Library.Resource.Attribute.stroke_join = SignatureCapture.Sample.Resource.Attribute.stroke_join;
			SignatureCapture.Library.Resource.Attribute.stroke_style = SignatureCapture.Sample.Resource.Attribute.stroke_style;
			SignatureCapture.Library.Resource.Attribute.stroke_width = SignatureCapture.Sample.Resource.Attribute.stroke_width;
			SignatureCapture.Library.Resource.Color.signaturecapture_black = SignatureCapture.Sample.Resource.Color.signaturecapture_black;
			SignatureCapture.Library.Resource.Color.signaturecapture_white = SignatureCapture.Sample.Resource.Color.signaturecapture_white;
			SignatureCapture.Library.Resource.Id.bevel = SignatureCapture.Sample.Resource.Id.bevel;
			SignatureCapture.Library.Resource.Id.butt = SignatureCapture.Sample.Resource.Id.butt;
			SignatureCapture.Library.Resource.Id.fill = SignatureCapture.Sample.Resource.Id.fill;
			SignatureCapture.Library.Resource.Id.fill_and_stroke = SignatureCapture.Sample.Resource.Id.fill_and_stroke;
			SignatureCapture.Library.Resource.Id.miter = SignatureCapture.Sample.Resource.Id.miter;
			SignatureCapture.Library.Resource.Id.round = SignatureCapture.Sample.Resource.Id.round;
			SignatureCapture.Library.Resource.Id.square = SignatureCapture.Sample.Resource.Id.square;
			SignatureCapture.Library.Resource.Id.stroke = SignatureCapture.Sample.Resource.Id.stroke;
			SignatureCapture.Library.Resource.Styleable.signaturecapture = SignatureCapture.Sample.Resource.Styleable.signaturecapture;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_background_color = SignatureCapture.Sample.Resource.Styleable.signaturecapture_background_color;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_paint_color = SignatureCapture.Sample.Resource.Styleable.signaturecapture_paint_color;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_stroke_cap = SignatureCapture.Sample.Resource.Styleable.signaturecapture_stroke_cap;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_stroke_join = SignatureCapture.Sample.Resource.Styleable.signaturecapture_stroke_join;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_stroke_style = SignatureCapture.Sample.Resource.Styleable.signaturecapture_stroke_style;
			SignatureCapture.Library.Resource.Styleable.signaturecapture_stroke_width = SignatureCapture.Sample.Resource.Styleable.signaturecapture_stroke_width;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int stroke_caps = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int stroke_joins = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int stroke_styles = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int stroke_widths = 2131165184;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int background_color = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int paint_color = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int stroke_cap = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int stroke_join = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int stroke_style = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int stroke_width = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int signaturecapture_black = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int signaturecapture_white = 2131034112;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000a
			public const int StrokeOkButton = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int StrokeWidth = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int bevel = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int butt = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int capture_view = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int fill = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int fill_and_stroke = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int miter = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int round = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int square = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int stroke = 2130968581;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int stroke_width = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] signaturecapture = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int signaturecapture_background_color = 2;
			
			// aapt resource value: 0
			public const int signaturecapture_paint_color = 0;
			
			// aapt resource value: 3
			public const int signaturecapture_stroke_cap = 3;
			
			// aapt resource value: 4
			public const int signaturecapture_stroke_join = 4;
			
			// aapt resource value: 5
			public const int signaturecapture_stroke_style = 5;
			
			// aapt resource value: 1
			public const int signaturecapture_stroke_width = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
